<form action="<?php echo $app['url_generator']->generate('categorias_save'); ?>" method="post" autocomplete="off">

    <?php if( isset($form['data']['id']) ) : ?>
        <input type="hidden" name="id" value="<?php echo $form['data']['id']; ?>">
    <?php endif; ?>

    <label for="titulo">Título</label><br>
    <input type="text" name="titulo" id="titulo" value="<?php echo isset($form['data']['titulo']) ? $form['data']['titulo'] : '' ?>">

    <br><br>
    <input type="submit" value="Enviar">

</form>